[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com; img-src 'self' https://pbs.twimg.com https://twitter-avatar.now.sh https://pixel.thesemetrics.org; frame-src 'self' https://www.youtube-nocookie.com"
    X-Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com; img-src 'self' https://pbs.twimg.com https://twitter-avatar.now.sh https://pixel.thesemetrics.org; frame-src 'self' https://www.youtube-nocookie.com"
    X-WebKit-CSP = "default-src 'self'; script-src 'self' https://unpkg.com; img-src 'self' https://pbs.twimg.com https://twitter-avatar.now.sh https://pixel.thesemetrics.org; frame-src 'self' https://www.youtube-nocookie.com"
    Feature-Policy = "fullscreen 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
